### ISSUE TITLE
4.0 How to migrate from Talker.good() (& others?)

### ISSUE THREAD

**Issue by Reprevise** [Frezyx/talker#176]
I'm not sure how to migrate from Talker.good(). There's no mention of its removal that I can find in the changelog, and I also can't find a migration guide posted anywhere. Also, `WellKnownTitles` has been removed, and I assume has been replaced with `TalkerLogType`, but there's no `title` property on that either.

**Comment by Frezyx** [comment]
Hello @Reprevise ! 

1) The method and level goog() have been removed due to infrequent usage in order to streamline the project's internal code. If desired, you can create your own extension, within the code of which you will use a custom log (inherit TalkerLog).

For more details, check [this part](https://github.com/Frezyx/talker?tab=readme-ov-file#custom-logs) in documentation 

2) Please provide your WellKnownTitles usage code.

**Comment by K1yoshiSho** [comment]
@Frezyx You should also make the colors specified in custom logs be pulled into TalkerScreen. There seems to be no way to change this, unless you specify TalkerLog type from the available ones. 🙌🏻
